name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script defined, skipping"
          fi

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: Build
        run: npm run build

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage
            coverage/lcov.info
